### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by fstecker** [criticic/llpp#11]
@marsam asked to create a new release tag to make the latest changes easier to include in the NixOS repository. The changes since the last tag (v41) have been compatibility with OCaml 5.0, libmupdf 1.23.5 and bash 5.2.

In the past, releases have been created and signed by @criticic, but he doesn't seem to be around here all that much recently. (Which is of course totally ok, please don't read this in a negative way. Thank you so much for making this repo in the first place!) So I suggest we just wait, say until the end of the week, and if he doesn't show up by then I'll make an (unsigned) v42 tag. Unless anyone has a better idea, of course.

**Comment by criticic** [comment]
I have added the new release tag. @marsam @fstecker you guys can update the respective packages now.

**Comment by fstecker** [comment]
Great, thank you @criticic !
